### ISSUE TITLE
More explicit names for `acl:accessTo` and `acl:default` predicats

### ISSUE THREAD

**Issue by joeitu** [solid/web-access-control-spec#103]
Hello,

If I understand correctly `accessTo` and `default` are closely related: one allows the authorization to the specified resource and the other allows access to the resources and recursively all the resources that it contains. 

I think that both words don't describe very well what they do. Also both words are too different while achieving similar goal. Likewise, thinking that the fact that one is recursive and the other is not could be explicit. 
Would it makes sense to replace them with something like:
`accessOnlyTo` and `accessRecursivelyTo`

**Comment by csarven** [comment]
Naming things is hard.

Renaming would be quite costly to deployed software in addition to handling security considerations. I do not see a clear benefit.

A container's ACL resource with an Authorization rule including `acl:default` is applicable only when the requested resource's associated ACL resource doesn't have a representation ( https://solid.github.io/web-access-control-spec/#effective-acl-resource-algorithm , https://solid.github.io/web-access-control-spec/#acl-default , http://www.w3.org/ns/auth/acl#default ) . It is not about applying recursively from the container to contained resources.

I find "accessTo" and "default" are simple enough terms and with sufficiently clear definitions, but I may not be best judge of this at this point in time.

If you are satisfied with this answer, feel free to close the issue.
