### ISSUE TITLE
definition and purpose of acl:GroupListing

### ISSUE THREAD

**Issue by elf-pavlik** [solid/web-access-control-spec#16]
https://github.com/solid/web-access-control-spec#groups-of-agents

Class `acl:GroupListing` doesn't seem to have any purpose, all groups have WebID (IRI denoting the instance of `vcard:Group`) and giving additional class to `foaf:Document` which has as its topic / describes one or more instances of `vcard:Group` doesn't seem to have any advantages.

> The object of an agentGroup statement is a link to a Group Listing document.

It seems that WebID of a group gets used

```
    acl:agentGroup <https://alice.example.com/work-groups#Accounting>;
    acl:agentGroup <https://alice.example.com/work-groups#Management>.
```

and not the URL of the document `<https://alice.example.com/work-groups>`

**Comment by timbl** [comment]
Agreed
