### ISSUE TITLE
object of statements with acl:default predicate

### ISSUE THREAD

**Issue by elf-pavlik** [solid/web-access-control-spec#18]
https://github.com/solid/web-access-control-spec#default-inherited-authorizations

```ttl
# [...]
<#authorization1>
    a acl:Authorization;
# [...]
    acl:accessTo <https://alice.databox.me/docs/>;
# [...]
    acl:defaultForNew <https://alice.databox.me/docs/>.
```

1. Can statements with subject `<#authorization1>` and predicates `acl:accessTo` and `acl:defaultForNew` can have different objects?
2. When this authorization gets applied to a document which object of `acl:accessTo` have `ldp:contains` relationship with. It seems that we get mismatch of `acl:accessTo` object (see #17 )
3. Can instead instance of `ldp:Container` itself use predicate like `acl:default` with an object of ACL document that documents which this container relates to via 'ldp:contains' and within don't have dedicated ACL will inherit.

**Comment by csarven** [comment]
Closing this issue as consensus is deemed to be captured in WAC Editor's Draft: https://solid.github.io/web-access-control-spec/ . See #access-objects #authorization-conformance #authorization-matching .
