### ISSUE TITLE
Status of planned `acl:defaultForNew` to `acl:default` change

### ISSUE THREAD

**Issue by zimeon** [solid/web-access-control-spec#20]
The note:

> *Note:* The `acl:defaultForNew` predicate will soon be renamed to `acl:default`, both in the specs and in implementing servers. The semantics, as described here, will remain the same

was added in [April 2016](https://github.com/solid/web-access-control-spec/commit/584ee12b283dc3c671e8b0fefc5c177aaa98d998) and I see referenced in https://github.com/solid/solid/issues/100 created at the same time. 

Do you have any idea of the likely timeline for this change to be implemented? We'd like to use the correct term in the [Fedora API specification](https://github.com/fcrepo/fcrepo-specification/issues/164) but also agree that `acl:default` is much less misleading than `acl:defaultForNew`.

**Comment by dmitrizagidulin** [comment]
@zimeon Thanks for checking. We're part of the way through transitioning to using just `acl:default` -- some of our ACL libraries check for either predicate, for backwards compatibility.
The next steps for us would be - updating the rest of the ACL-related code to be able to parse either, and to update the spec.

My personal (non-official) opinion is that you guys should just go ahead with `acl:default` in implementing your servers.

**Comment by zimeon** [comment]
@dmitrizagidulin Is there any chance that `acl:default` might be added to the ACL vocabulary http://www.w3.org/ns/auth/acl ? That would give a little more confidence in moving with that ahead of the spec

**Comment by dmitrizagidulin** [comment]
@zimeon good idea; I'll see if we can do it tomorrow.

**Comment by dmitrizagidulin** [comment]
@zimeon - `acl:default` should now be added to http://www.w3.org/ns/auth/acl, along with a deprecation note for `defaultForNew`. 
We've started the process of making sure all our libs support `acl:default`, etc. Thanks again.

**Comment by kjetilk** [comment]
To update on this, the actual change will happen in 5.0.0, which is due very soon.

**Comment by Otto-AA** [comment]
I'm currently writing an acl library and would like to know if this change already landed on the new NSS version (on the pod I'm using it is still using "defaultForNew" when I create new folders and update the permissions).

And would it be safe to just add a "default" predicate with the same value? So the acl file has both versions and can be used with "old" apps and "new" apps.

**Comment by kjetilk** [comment]
> I'm currently writing an acl library and would like to know if this change already landed on the new NSS version (on the pod I'm using it is still using "defaultForNew" when I create new folders and update the permissions).

Yes, `default` is now in the released and deployed NSS.

> And would it be safe to just add a "default" predicate with the same value? So the acl file has both versions and can be used with "old" apps and "new" apps.

Yeah, we're basically treating it as an alias.
