### ISSUE TITLE
[Question] Enforcement

### ISSUE THREAD

**Issue by LoveIsGrief** [solid/web-access-control-spec#28]
Hello,

I've been reading through the spec and cannot find any mention on who enforces the WAC nor how.

The assumptions here (I haven't read all the specs, so I hope I'm wrong) are:
 - user data is encrypted
 - user data is distributed across multiple pods
 - each pod can mirror another
 - when a pod goes down or is otherwise perturbed, a user can access their data using any other pod in the system

If these assumptions are true, then how would the system be pod ecosystem protect itself against evil actors that provide pods (or clients) ignoring WACs?

Links to further reading are very welcome.

Cheers

**Comment by csarven** [comment]
>    user data is encrypted

currently not.

>    user data is distributed across multiple pods

currently not.

>    each pod can mirror another

potentially.

>    when a pod goes down or is otherwise perturbed, a user can access their data using any other pod in the system

there is particular hard connection between different pods.

**Comment by LoveIsGrief** [comment]
Well... that doesn't bode well for privacy. The pod operator/host will have access to all information :/ That's a pity.

Thanks for the response

**Comment by csarven** [comment]
Needless to say, the specs and the implementations will evolve. I was only reflecting on the current state. Just to add:

Encrypted pods on a shared dataspace will become even more important and a hard-requirement. Just to compare to 'common' shared-hosting services, an account's data is usually not encrypted. What's in place now matches the common practice, but we are not limited to or stuck there.

As for distributing or mirroring data across pods, that may be implementation specific, or generally part of functions that sync, backup or archive. This is useful of course in and itself, but being able to *use any copy from anywhere* may be outside of the current architecture.

WAC is not simply ignored. There are other assumptions that's taken for granted. It is about where a user places their "trust". If they trust the admins of the system, the rest follows. That is not solely about whether data is encrypted or not. There are many other data items that can be collected in a shared dataspace eg. network connections.

**Comment by LoveIsGrief** [comment]
My question has been answered.

Cheers and Merry Christmas :slightly_smiling_face:
