### ISSUE TITLE
I deleted my profile/card

### ISSUE THREAD

**Issue by aivorra** [solid/web-access-control-spec#29]
Hi, I'm testing solid and I deleted the profile/card. How can I recover it?
My account is https://afi.solid.community/

Best regards.

**Comment by timbl** [comment]
- Go to the folder which contained the card
- Press the green plus and then the source code icon to make a new text file
- give card.ttl as the file name
- Go to the card in databrowser then, 
- Use the profile editor pane to edit it (this is available like the home pane all the time)

**Comment by timbl** [comment]
But  closing this -- as now a WAC issue.
