### ISSUE TITLE
ACL Ontology Inaccuracies 

### ISSUE THREAD

**Issue by kidehen** [solid/web-access-control-spec#30]
The ACL Ontology provides a canonical  source of information for Solid ACL processors. Thus, we need entity relationship types (relations) defined in the ontology to clearly inform said processors about the accepted domains and ranges of relations (rdf:Property class instances). 

Currently, we have the following inaccuracy, with regards to property value ranges:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . 
@prefix acl: <http://www.w3.org/ns/auth/acl#> . 
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . 

acl:mode a rdf:Property ;
                    rdfs:range rdfs:Class .
```

Correction:

```
## Indicating that acl:mode is a relationship type (rdf:Property instance)
## that expects its object (value) to be 
## an instance of an acl:Access class

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . 
@prefix acl: <http://www.w3.org/ns/auth/acl#> . 
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . 

acl:mode a rdf:Property ;
                     rdfs:range acl:Access .
```

**Comment by timbl** [comment]
Actually modes ARE classes…. so the mode predicate takes a class as it object.
```
   acl:Read     a :Class;
         :comment "The class of read operations";
         :label "read"@en;
         :subClassOf acl:Access .
```
If we  had rdfs:range acl:Access; then a specific access (like a fetch which happened today) woul have to be given.

**Comment by kidehen** [comment]
@timbl ,

The semantics of [rdfs:range](https://www.w3.org/TR/rdf-schema/#ch_range) state:

> rdfs:range is an instance of rdf:Property that is used to state that the values of a property are instances of one or more classes.

> The triple P rdfs:range C
states that P is an instance of the class rdf:Property, that C is an instance of the class rdfs:Class and that the resources denoted by the objects of triples whose predicate is P are instances of the class C.

Thus:
acl:mode a rdf:Property ;
                rdfs:range acl:Access .

Then:
URIs that identify instances of subclasses of acl:Access are then valid. 

Example:
<#someAuthorization> acl:mode acl:Control .

[This follow-your-nose friendly page](http://linkeddata.uriburner.com/describe/?url=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23mode&graph=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl&distinct=1) also demonstrates the current problem. 

Also note,  [this actual description of one of the incarnations of RWWCrew ACL](http://linkeddata.uriburner.com/describe/?url=https%3A%2F%2Fkidehen2.solid.openlinksw.com%3A8444%2Fpublic%2Frww-crew-acl.ttl%23RWWCrew&invfp=IFP_OFF&sas=SAME_AS_OFF&distinct=1) .

**Comment by elf-pavlik** [comment]
> The triple P rdfs:range C
states that P is an instance of the class rdf:Property, that C is an instance of the class rdfs:Class and that the resources denoted by the objects of triples whose predicate is P are **instances of the class C**

.I think modes stay defined as subclasses of `acl:Access` not instances of it
`acl:Read rdfs:subClassOf acl:Access .` vs `acl:Read a acl:Access .`

so current range seems to fit definition of `rdfs:Class`
> This is the class of resources that are RDF classes. `rdfs:Class` is an instance of `rdfs:Class`.

**Comment by kidehen** [comment]
@elf-pavlik,

acl:Access as object of acl:mode relation addresses the fact that acl:Read rdfs:subClassOf acl:Access.

How come the object of acl:mode isn't rdf:Class then? 

rdfs:range and rdfs:domain is how you assert:

This relationship type is an association between two types of things. In this case, we are saying that an acl:mode is a relationship that associates an Authorization with an Access -- both [Authorization](http://linkeddata.uriburner.com/describe/?url=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23Authorization&graph=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl&distinct=1) and [Access](http://linkeddata.uriburner.com/describe/?url=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23Access&graph=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl&distinct=1) are classes (not instances of classes). 

Why is this important? Just click on the sample links in [my reply](https://github.com/solid/web-access-control-spec/issues/30#issuecomment-428735915) to @timbl .

Following-your-nose (as a human) and understanding what's presented is exactly what happens to an RDF-processor (machine) that tries to understand the nature of the relationship type (relation) and the things it associates -- by way of what's expressed in rdfs:domain and rdfs:range relations. 

BTW -- I haven't said that rdfs:range of [acl:mode relation](http://linkeddata.uriburner.com/describe/?url=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23mode&graph=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl&distinct=1) is an instance of a class. I am saying that the URI that identifies the object of that relation should identify the class [acl:Access](http://linkeddata.uriburner.com/describe/?url=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23Access&graph=http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl&distinct=1) rather than rdfs:Class.

**Comment by elf-pavlik** [comment]
> This relationship type is an association between two entity types (class of things). In this case, we are saying that an acl:mode is a relationship that associates an Authorization with an Access -- **both Authorization and Access are classes (not instances of classes)**.

Looking at example you provided in

> Also note, [this actual description of one of the incarnations of RWWCrew ACL](http://linkeddata.uriburner.com/describe/?url=https%3A%2F%2Fkidehen2.solid.openlinksw.com%3A8444%2Fpublic%2Frww-crew-acl.ttl%23RWWCrew&invfp=IFP_OFF&sas=SAME_AS_OFF&distinct=1)

```ttl
<#RWWCrew>
    a acl:Authorization ;
    acl:agent turnguard:me, timbl:i, melvin:me, ruben:me, kidehen:i, kidehen5-solid:me, 
			  kidehen7-solid:me, smalinin:identity, software-agent:i, csarven:i, ruben-solid:me, 
			  kidehen-solid:me, cmsb:identity, kidehen2-solid:me, kjetil:me, tallted:me ;
    acl:defaultForNew <./> ;
    acl:mode acl:Read, acl:Write .
```

I see here a statement
```ttl
<#RWWCrew> acl:mode acl:Read .`
```

where we have
```ttl
<#RWWCrew> a acl:Authorization . # an instance of acl:Authorization
acl:Read rdfs:subClassOf acl:Access . #an subclass of acl:Access => instance of rdfs:Class
```

so statement with predicate `acl:mode`, appears to have **an instance** of `acl:Authorization` as subject but **a subclass** of `acl:Access` (instance of rdfs:Class`) as object.

Wouldn't rdfs reasoner given suggested by you
```ttl
acl:mode rdfs:range acl:Access
```

infer triple
```ttl
acl:Read a acl:Access . # so rdf:type not rdfs:subClassOf
```

As I understood @timbl's comment we should consider each request made to the resource as an instance of `acl:Access` and its more specific subclasses. So when I do

```http
GET /solid/web-access-control-spec/issues/30 HTTP/1.1
User-Agent: HTTPie/0.9.9
Accept: */*
Host: github.com
```

This specific request I made becomes an instance of `acl:Read`

```ttl
:_r0 a acl:Read .
```

and RDFS reasoner based on `acl:Read rdfs:subClassOf acl:Access` can infer

```ttl
:_r0 a acl:Access .
```

given that, inference resulting from change to `rdfs:range` you suggest

```ttl
acl:Read a acl:Access . # so rdf:type not rdfs:subClassOf
```

doesn't seem to describe `acl:Read` as intended by this ontology.

**Comment by kidehen** [comment]
@elf-pavlik ,

So the idea that @timbl was describing in his earlier response is as follows:

The object of an acl:mode relation is set to an rdfs:Class for maximum extensibility purposes. Basically, as new types of acl modalities arise they can be incorporated into an ACL.

Very similar to how acl:agentClass relation which enables use of vcard:Group, foaf:Agent to broaden scope of a acl:Authorization. 

Okay, the intended use is clear now.
