### ISSUE TITLE
Document WAC-Allow header

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#43]

**Comment by michielbdejong** [comment]
As implemented in https://github.com/solid/wac-allow

**Comment by michielbdejong** [comment]
Seems that this is an undocumented spec feature that NSS does implement and that some apps are using?

**Comment by csarven** [comment]
WAC-Allow is relatively new in WAC's timeline. IIRC, the functionality was initially requested so that apps can adapt their UI (eg. whether to enable or disable a 'Save' button) based on the revealed permissions on the resource given user's priviledges. In its absence, anapp has no idea whether it can or even should bother with a write operation for instance. Some background: https://github.com/linkeddata/dokieli/issues/96 , https://github.com/solid/solid/issues/45 

I still intend to implement it in dokieli ... :)

I suggest to document/review server/client implementation/use of WAC-Allow before spec'ing.

**Comment by michielbdejong** [comment]
@RubenVerborgh do you know if any apps currently use this when it's available?

It could be expensive to compute, for instance if a lot of people have Control access to a resource, then you need to fetch and parse all their profile documents before you know exactly which access modes would be allowed for the current combination of webId + origin.

**Comment by RubenVerborgh** [comment]
It was a feature that @timbl and I introduced in 2017, with the intention of it being used by Databrowser and other places.

I am using it in Mavo for Solid, and that's it I think.

> It could be expensive to compute, for instance if a lot of people have Control access to a resource, then you need to fetch and parse all their profile documents before you know exactly which access modes would be allowed for the current combination of webId + origin.

That operation should always be cheap though. For a given person, do they have this specific access right? (Enumeration might be expensive indeed.)

**Comment by michielbdejong** [comment]
It depends. :) In the simple case, there is a short ACL doc that either mentions the webId or not, and there is only one 'owner' who has control over the resource, and whose profile we need to check for acl:trustedApp. And in a lot of cases, that profile will live on the same server because it will be the pod owner. But two things can get expensice: lots of large acl:agentGroup rules on remote and slow servers, and especially if such an agent group then has acl:Control, worst case you need to retrieve all the profile documents to see all the acl:trustedApps list.
Access checking will usually be slower for negative than for positive cases. If I gave some app read access to /foo/bar.ttl and gave a bunch of other people Control access to it, then if I attempt to read the resource with that app, the server can quickly see that the app has read access in my trustedApps list, stop looking any further, and allow me to read it with that app. But the question of whether I, with that app, also has append access, would require retrieving all the profile docs of the co-owners of the doc. And if it's just for displaying it in a header which the app may not even use, then that's expensive.

**Comment by RubenVerborgh** [comment]
Fair enough. Although I still think we should be able to make the above fast (because we will need it), there will be an overhead if it needs to be done on every request (as opposed to only when writes are executed).

For the record: I am not a fan of the WAC-Allow header mechanism; I would want that metadata inside of the document. But regardless of the mechanism, you point stands indeed.

**Comment by RubenVerborgh** [comment]
Wait, none of the above is correct.

When a user accesses a document, their Read permissions need to be looked up anyway. And their Append/Write/Control permissions will be at the exact same place. (It is not possible to have different permissions bits of a document in different places.) So there is nothing that WAC-Allow requires that isn't already done.

This is why I cached these permissions in NSS: https://github.com/solid/node-solid-server/commit/180de68a2246758082a507b82d9d37ff3d60c922

**Comment by michielbdejong** [comment]
There are two ways in which your write permissions might be in a different ("further away") place than your read permissions:
1) the ACL doc gives you read access directly (maybe the resource is public-readable, for instance), but gives write access to an `acl:agentGroup` which on closer inspection happens to include you
2) the resource has multiple owners, one of whom has the current app (from the `Origin` header on the request) as an `acl:trustedApp` for Read, and the other one (whose profile might live on a very slow remote server) has it as an `acl:trustedApp` for Write.

**Comment by RubenVerborgh** [comment]
> * the ACL doc gives you read access directly (maybe the resource is public-readable, for instance), but gives write access to an `acl:agentGroup` which on closer inspection happens to include you

Correct.

My reasoning and implementation indeed predated agent groups.
(For which we probably also need caching, which would address this.)

> * the resource has multiple owners, one of whom has the current app (from the `Origin` header on the request) as an `acl:trustedApp` for Read, and the other one (whose profile might live on a very slow remote server) has it as an `acl:trustedApp` for Write.

But WAC-Allow is only concerned with a) the current user b) the public, so the remote user's prefs wouldn't apply to the current user?

**Comment by michielbdejong** [comment]
From https://github.com/solid/web-access-control-spec#possible-future:

> We define the owners of the resource as people given explicit Control access to it. (Possible future change: also anyone with Control access, even through a group, as the group can be used as a role)

> For each owner x, the server looks up the (extended?) profile, and looks in it for a triple of the form

That's what we implemented in Node-Solid-Server in March 2019.

**Comment by RubenVerborgh** [comment]
Okay, but we do not need to find all owners, do we?

Or does the above piece say that the set of allowed apps is the combined set of all apps by any user with Control permissions? (I really hope it does not.)

**Comment by TallTed** [comment]
> When a user accesses a document, their Read permissions need to be looked up anyway. And their Append/Write/Control permissions will be at the exact same place. (It is not possible to have different permissions bits of a document in different places.) So there is nothing that WAC-Allow requires that isn't already done.

1. An `ASK` query (the lowest-weight query for many things) checks only whether a `READ` permission exists. It reveals nothing about other permissions.  Checking whether a user (including "unknown user" a/k/a "the public" a/k/a `world`) can `READ` a resource does not (and I think should not) imply checking, learning, seeing, etc., anything about their other permissions on that or any other resource.  Indeed, exposing more than `TRUE`/`FALSE` on a single-resource `READ` question might be considered a vulnerability.  Checking `WRITE` or `EXECUTE` or other permission should not occur until the request to perform that action.

2. I think that whether these permissions will be at the exact same place depends on the back-end that's handling things. As this is about *spec* design, and not about NSS design, this is important. I think that running everything through text files which must be handled by text processors simply won't scale. Storing ACLs in a DB and making them available and/or editable via textual serialization (even if those serializations are persistent a/k/a serve as caches, in a way) does scale -- and also lets these permissions be distant from each other, through various kinds of partitioning. 

---

"...whether to show a SAVE button or not..."

If I can READ a resource, I should be able to edit (locally) what I've read.  Whether I can WRITE my edited version back to the original location (i.e., whether I can change the original resource) is a distinct question from whether I should (and I should!) be able to WRITE it *somewhere* -- so I should *always* get a `SAVE` (and a distinct `SAVE AS...`) button, which may then lead to different interactions if I cannot write to the location of the moment (which for `SAVE` should *try* the origin, and if not permitted, should proceed as if `SAVE AS...`, which should go through a "pick your location" process).

(This thread seems to be going rather far afield of what I would understand as "Document `WAC-Allow` header"...)

**Comment by RubenVerborgh** [comment]
Re: ASK query, sure, but my point is rather that finding the right
permissions block within the right file is the bottleneck; any resulting
query is simple once you know the applicable block.

**Comment by TallTed** [comment]
@RubenVerborgh - I'm saying that you don't necessarily need to know about what file(s) hold the relevant permissions block(s). You need to know there's been a request by `ex:Fred` to READ `ex:ResourceX`. So you query your permissions service, `ASK { ex:Fred ex:canREAD ex:ResourceX }`. The permissions service handles all the heavy lifting, and shows you nothing but `TRUE`/`FALSE`. You don't know whether the grant is based on `ex:Fred` explicitly, or on `ex:Fred` being a member of a group (at whatever recursion level), or on `ex:ResourceX` being `world:READ`. Likewise, you have no idea about any other permissions.

For purposes of the `WAC-Allow` header, there would be multiple `ASK` queries -- two (one for `currentuser` and one for `public`) per possible action/permission (`READ`, `WRITE`, `EXECUTE`, `CONTROL`, etc.) ... which would likely still be faster than digging through all relevant text files in the moment, and would still only reveal TRUE/FALSE for each permutation.

(I really wonder why the `public` aspect is necessary or even appropriate here. I would think that only the permissions for the current user, whether authenticated or not [making them `public`], are really necessary.)

Of course, this isn't how NSS does things, but this is [`web-access-control-spec`](https://github.com/solid/web-access-control-spec/), so....

**Comment by RubenVerborgh** [comment]
Agreed in general, but Michiel’s computation was for file-based. In
general, can be arbitrarily more expensive indeed.

**Comment by michielbdejong** [comment]
> does the above piece say that the set of allowed apps is the combined set of all apps by any user with Control permissions? (I really hope it does not.)

I do think that's what  https://github.com/solid/web-access-control-spec#possible-future says (unless I misread it), and that's also what we implemented in both NSS and wac-ldp.

**Comment by RubenVerborgh** [comment]
I think that's a mistake, we will need an issue on this. Certainly an issue to clarify the language so this is unambiguous, but also an issue to discuss what it is we really want.

**Comment by michielbdejong** [comment]
I we can make a note that NSS provides this, but I would say let's not include this in the spec.

**Comment by michielbdejong** [comment]
We discussed this during the weekly meeting; both @timbl and @dmitrizagidulin want this, so let's add it, then.
