### ISSUE TITLE
Can ACL docs be in JSON-LD?

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#45]
Since LDP officially supports JSON-LD as a 'SHOULD', it feels like the WAC spec should too, right? But when trying to write unit test for ACL docs in JSON-LD format, I ran into this problem:
```sh
 $ curl -H "Accept: application/ld+json" http://www.w3.org/ns/auth/acl
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>Not Acceptable</h1>
<p>An appropriate representation of the requested resource /ns/auth/acl could not be found on this server.</p>
Available variants:
<ul>
<li><a href="acl.ttl">acl.ttl</a> , type text/turtle</li>
<li><a href="acl.rdf">acl.rdf</a> , type application/rdf+xml</li>
<li><a href="acl.n3">acl.n3</a> , type text/n3</li>
</ul>
</body></html>
```

Should we ask the webmasters of w3.org to publish a JSON-LD representation of http://www.w3.org/ns/auth/acl?

**Comment by RubenVerborgh** [comment]
@timbl Could your script be extended to do that?

**Comment by leinue** [comment]
I want JSON-LD too.

**Comment by csarven** [comment]
WAC does not need to require more than one concrete RDF syntax. Only Turtle is required for interop. Requiring any additional syntax increases the complexity on the WAC-spec level. Servers implementing a protocol that supports JSON-LD (and/or other syntaxes) can do so.

Unless there is a compelling reason for WAC to support other syntaxes, I suggest to close this issue.

**Comment by elf-pavlik** [comment]
I think this issue was about vocab not the representation of ACLs in given ecosystem.

**Comment by csarven** [comment]
hah! oops, I've totally lazy-misread that.

Source is acl.n3 . I don't see a particular reason not to have a JSON-LD representation...  will followup with Tim/Eric.

**Comment by TallTed** [comment]
I'm confused.

To my eyes, it looks like @elf-pavlik misread the original post. I don't see a question about vocab, but about whether JSON-LD representations of ACLs could be supported -- where TTL, RDF/XML, and N3 already are. ... 

I also don't see how @csarven's latest addresses a vocab question, when you're going to follow up with people about delivering a JSON-LD representation of an N3 resource ... but it does seem to be addressing the original question.

Have I lost the plot somewhere?

**Comment by csarven** [comment]
@TallTed 

I can see that there are two things being conflated. The title of the issue:

>Can ACL docs be in JSON-LD?

and the following line caused the confusion:

>Since LDP officially supports JSON-LD as a 'SHOULD', it feels like the WAC spec should too, right? But when trying to write unit test for ACL docs in JSON-LD format, I ran into this problem:

because they they have nothing to do with what follows:

>curl -H "Accept: application/ld+json" http://www.w3.org/ns/auth/acl

>Should we ask the webmasters of w3.org to publish a JSON-LD representation of http://www.w3.org/ns/auth/acl?

I overlooked some details in my original comment hence the reason why I thought it is about the ACL resource as opposed to the ACL ontology.

@michielbdejong ? :)

**Comment by michielbdejong** [comment]
Sorry, I didn't remember the details but if you follow the link to https://github.com/inrupt/wac-ldp/issues/45#issuecomment-490979957 and https://github.com/inrupt/wac-ldp/commit/78a40a7d477a633ef8b0353b2d3378991a58af2a that gives some more info.

So while we could still ask the webmasters of w3.org to publish a JSON-LD representation of http://www.w3.org/ns/auth/acl, the answer to this issue is of course "yes, they can". And as long as clients don't try to retrieve http://www.w3.org/ns/auth/acl to get context, all is fine!
