### ISSUE TITLE
[discuss] should we switch to requiring container-write instead of resource-write permissions for delete?

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#47]
This spec clearly states that it requires `acl:Write` on the resource, but in https://github.com/solid/node-solid-server/issues/729 NSS diverged from the spec.

In https://github.com/solid/node-solid-server/issues/729#issuecomment-409987766 @dmitrizagidulin correctly remarked that this should be made into a spec-level discussion, but it seem that his remark was ignored?

So let's have the discussion now!

Pro change:
* NSS implementers have already diverged from the spec at this point, and even though they didn't follow process, it would be practical to retro-actively agree with them
* It aligns WAC more with how the Linux file system works

Con change:
* All changes cost work, and this one is no exception
* even though NSS may have made this change, inrupt/pod-server has not, so for the current implementations it's 1 against 1. @acoburn what does your Trellis extension for WAC do on this topic?
* As remarked in https://github.com/solid/node-solid-server/issues/729#issuecomment-409987242, and I agree, the current spec makes more sense.
* It's weird if DELETE requires different permissions than PUT
* If we do want to separate the two, it would make more sense to split `acl:Write` into `acl:Create`, `acl:Update`, and `acl:Delete`.
* Now that I write this, I realize that the distinction is not just update/delete, it's create/update/delete, which makes it.

**Comment by RubenVerborgh** [comment]
General note regarding changes:
let us not be influenced too much by what exist. Many things were fast/pragmatic choices, many of which were never discussed or thought through. We still have the luxury of changing things at this point; that luxury will likely have disappeared within a year.

**Comment by RubenVerborgh** [comment]
>     * As remarked in [solid/node-solid-server#729 (comment)](https://github.com/solid/node-solid-server/issues/729#issuecomment-409987242), and I agree, the current spec makes more sense.

No cherry-picking please 😛

https://github.com/solid/node-solid-server/issues/729#issuecomment-409988794 follows up

**Comment by michielbdejong** [comment]
I have implemented the current spec in pod-server, which means `acl:Write` on the resource for create, update, as well as delete. So if in this issue we decide to change the spec, that will mean NSS becomes compliant, but pod-server will stop being compliant.

**Comment by csarven** [comment]
Closing this issue as consensus is deemed to be captured in WAC Editor's Draft: https://solid.github.io/web-access-control-spec/ . See #authorization-evaluation #reading-writing-resources #access-mode-extensions . See also https://github.com/solid/web-access-control-spec/issues/85
