### ISSUE TITLE
say something about trailing slashes

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#49]
In https://www.w3.org/TR/ldp-bp/#include-a-trailing-slash-in-container-uris it's recommended to refer to a container with a trailing slash, but i think it can be expected of a server to add that trailing slash if it's missing?
For instance I I write:
```turtle
<#owner> acl:accessTo <https://mypod.com/foo> .
```
in https://mypod.com/foo/.acl then the server should interpret that as
```turtle
<#owner> acl:accessTo <https://mypod.com/foo/> .
```

**Comment by michielbdejong** [comment]
remark from @timbl in weekly meeting: if there's no trailing slash, then there's no match

**Comment by csarven** [comment]
Specs ought to develop independently, and should not be based on a particular implementation or convention. That goes for WAC not having knowledge or dependency on LDP or expect that WAC should follow a specific URI Template.
