### ISSUE TITLE
Compare webid-oidc to IndieAuth

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#52]
See https://indieweb.org/How_is_IndieAuth_different_from_OpenID_Connect for inspiration

**Comment by csarven** [comment]
Okay to compare with OpenID Connect and what webid-oidc introduces. However, don't bother with comparisons to arbitrary implementations/layers out there so as to to not overload the reader with what's not essential to know for the spec here.

**Comment by michielbdejong** [comment]
right, good point, it should not be in the introduction for the audience of this doc since most readers will not know indieauth. we should put it in a separate place then, maybe in some FAQ somewhere

**Comment by michielbdejong** [comment]
i guess my main question is why does indieauth not have session management, because other than that, it seems very similar to webid-oidc

**Comment by michielbdejong** [comment]
Ah and oops, wrong repo, moved to https://github.com/solid/webid-oidc-spec/issues/29
