### ISSUE TITLE
Update vocabulary

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#53]
Related to #51, both [wiki-flavoured](https://www.w3.org/wiki/WebAccessControl#Vocabulary) and [solid-flavoured](https://github.com/solid/web-access-control-spec) WAC use the http://www.w3.org/ns/auth/acl vocabulary. Although it looks like it's more or less sufficient for wiki-flavoured WAC, there are definitely things missing from it that we do use here (like acl:trustedApp, for instance). We should either update the existing vocabulary or create a new one.

**Comment by csarven** [comment]
AFAICT, everything that WAC ED requires and non-conflicting is in the ACL ontology. Not sure if there is anything that needs to be done further.
