### ISSUE TITLE
Can one acl file be used for multiple individual resources?

### ISSUE THREAD

**Issue by Otto-AA** [solid/web-access-control-spec#61]
We are currently rewriting the solid-file-client library and for deleting files the question came up, if multiple files can share the same .acl file. We know that this is possible by inheriting from a folder, but wonder if it is also possible by directly linking to the same file.

Example:
```
foo/first.ttl     <Link: <common.acl>; rel="acl"
foo/second.ttl    <Link: <common.acl>; rel="acl"
foo/common.acl
```

**Comment by michielbdejong** [comment]
yes, this is possible (although NSS doesn't do this).

**Comment by Otto-AA** [comment]
Ok, thanks for the info :+1:
