### ISSUE TITLE
Clarify "case as a group"

### ISSUE THREAD

**Issue by tmciver** [solid/web-access-control-spec#72]
In the README there is the following sentence:

> An application of this feature is to throw a resource open to all logged on users for a specific amount of time, accumulate the list of those who case as a group, and then later restrict access to that group, to prevent spam.

The question here is around the use of the word "case".  Is it a typo or meant in the sense of "to examine or survey"?  If the latter, I would suggest changing this wording as it sounds strange to my ear, er, looks strange to my eye. :)

**Comment by dmitrizagidulin** [comment]
+1, I also don't understand that sentence.
