### ISSUE TITLE
Is acl:Authorization mandatory?

### ISSUE THREAD

**Issue by Otto-AA** [solid/web-access-control-spec#78]
Does every authorization needs a `acl:Authorization` statement? I've seen it being used in all examples and (nearly) all implementations, but I didn't find a statement if it is necessary. I think it would be useful for acl-parsers to differ between authorizations and other quads.

**Comment by csarven** [comment]
We need a shape for ACLs.

**Comment by Otto-AA** [comment]
I see how this could prove useful in the future, but imo this doesn't clarify if we should make `acl:Authorization` statements mandatory for now or not.

**Comment by acoburn** [comment]
This issue is being discussed at https://github.com/solid/specification/issues/57

**Comment by Otto-AA** [comment]
Thanks for this reference. I think we should update the spec here once the other issue is resolved, so I'd keep this issue open for now.

**Comment by csarven** [comment]
Thanks for this issue and discussion. Closing this issue as consensus is deemed to be captured in WAC Editor's Draft: https://solid.github.io/web-access-control-spec/ . See #authorization-conformance
