### ISSUE TITLE
Clarify: 'acl' rel link is a naming hint, not always points to existing file

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/web-access-control-spec#8]
Add an explanation to the ACL Resource Discovery section that the `rel="acl"` link will be returned even if no actual individual `.acl` file is present. That is, it's a naming hint, and not necessarily a link to an existing ACL resource.

**Comment by Otto-AA** [comment]
From my interpretation "a client can discover the location of its corresponding ACL" indicates that the ACL file actually has to exist if the link value is present. Therefore I would also welcome clarification on that.

**Comment by dmitrizagidulin** [comment]
@Otto-AA Yeah, exactly, the spec wording sort of implies that the file exists.
Whereas that's not the case, it's more like "if it _were_ to exist, this is what it would be" -- it's most often just a naming hint.

**Comment by csarven** [comment]
RFC 8288:

>[Link Relation Types by definition] only describe how the
   current context is related to another resource.

Closing this issue as consensus is deemed to be captured in WAC Editor's Draft: https://solid.github.io/web-access-control-spec/ . https://solid.github.io/web-access-control-spec/#acl-resources details ACL resource discovery and representation, and there is no requirement that an ACL resource needs to have a representation. https://solid.github.io/web-access-control-spec/#effective-acl-resource-algorithm includes the case where an ACL resource may not have a representation.
