### ISSUE TITLE
Delegated Requests

### ISSUE THREAD

**Issue by elf-pavlik** [solid/web-access-control-spec#9]
https://github.com/solid/solid/blob/auth-webid-delegation/proposals/auth-webid-delegation.md

> IMPORTANT: The reason why the delegatee must use its own identity (i.e. https://alice.example.org/agent#i) and credentials, is to avoid confusion as to who is actually performing the request. This is particularly important when applying access control policies, as we could imagine that certain resources may not be accessible for certain agents (delegatees).

I don't see in current draft any information on how to allow or disallow delegated requests.

**Comment by dmitrizagidulin** [comment]
Yeah. I've personally been avoiding delving into that topic until we sort out auth'n.

**Comment by deiu** [comment]
Indeed. We're interested in supporting this feature but we're current waiting for an actual use case before we spend more time looking into it.

**Comment by namedgraph** [comment]
The examples really should be updated and aligned with https://www.w3.org/wiki/WebID/Authorization_Delegation which uses `cert:secretary` (not defined in http://www.w3.org/ns/auth/cert#) which is the inverse of `acl:delegates`.

**Comment by elf-pavlik** [comment]
I think it also affects how *Origin* restrictions work, I don't think we can expect requests from delegatees to have some specific Origin. It also relates to https://github.com/solid/webid-oidc-spec/issues/9 since delegatees also fit 'server side client' role.

**Comment by elf-pavlik** [comment]
Current work in authorization panel will treat all authorized request, not made by navigating browser directly to requested resource, as delegated request. OAuth2 provides robust framework for delegating access. User will have full control over what subset of one's own access gets delegated to the client/app.
